"""initial_tables

Revision ID: 0439c2ff14e1
Revises: d83f1dcc553e
Create Date: 2026-03-08 00:30:33.461916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0439c2ff14e1'
down_revision: Union[str, None] = 'd83f1dcc553e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
