"""add_geolocation_fields_to_addresses

Revision ID: 24dcea57a231
Revises: 8b544e35619f
Create Date: 2026-03-20 11:25:15.617928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24dcea57a231'
down_revision: Union[str, None] = '8b544e35619f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('flat_number', sa.String(length=50), nullable=True))
    op.add_column('addresses', sa.Column('house_number', sa.String(length=50), nullable=True))
    op.add_column('addresses', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('addresses', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'longitude')
    op.drop_column('addresses', 'latitude')
    op.drop_column('addresses', 'house_number')
    op.drop_column('addresses', 'flat_number')
    # ### end Alembic commands ###
