"""expand_otp_code_column_to_varchar20

Revision ID: a3ac877834ef
Revises: a924d2065741
Create Date: 2026-03-08 19:48:33.794919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ac877834ef'
down_revision: Union[str, None] = 'a924d2065741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_codes', 'code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_codes', 'code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
